### ISSUE TITLE
pull & compile

### ISSUE THREAD

**Issue by thanhhainguyen15** [CEA-LIST/Cingulata#12]
Please tell me how to fix it !
build$ cmake ..
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.5/Modules/ExternalProject.cmake:1809 (message):
  error: could not find hg for clone of abc
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  optim/CMakeLists.txt:5 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!

**Comment by ssmiler** [comment]
Install all prerequisites:
https://github.com/CEA-LIST/Cingulata/wiki/install_os
In particular `sudo apt-get install mercurial`

**Comment by sergiu-carpov** [comment]
Install all prerequisites:
https://github.com/CEA-LIST/Cingulata/wiki/install_os
In particular `sudo apt-get install mercurial`

**Comment by sergiu-carpov** [comment]
Install all prerequisites:
https://github.com/CEA-LIST/Cingulata/wiki/install_os
In particular `sudo apt-get install mercurial`
