### ISSUE TITLE
Error during exec make

### ISSUE THREAD

**Issue by thanhhainguyen15** [CEA-LIST/Cingulata#13]
I found another issue during compilation
build$ make -j 8
Scanning dependencies of target abc
Scanning dependencies of target helper
Scanning dependencies of target generator
Scanning dependencies of target fhe_fv
[  1%] Creating directories for 'abc'
[  2%] Building CXX object runtime/fhe_apps/src/CMakeFiles/helper.dir/helper.cxx.o
[  3%] Building CXX object circuit/generator/src/CMakeFiles/generator.dir/bit-tracker.cxx.o
[  5%] Building CXX object circuit/generator/src/CMakeFiles/generator.dir/circuit.cxx.o
[  5%] Building CXX object circuit/generator/src/CMakeFiles/generator.dir/node.cxx.o
[  6%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/ciphertext.cxx.o
[  7%] Building CXX object circuit/generator/src/CMakeFiles/generator.dir/storage.cxx.o
[  8%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/encdec.cxx.o

[  9%] Performing download step (hg clone) for 'abc'
[ 10%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/fhe_params.cxx.o
[ 11%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/keygen.cxx.o
abort: could not find web.cacerts: /etc/ssl/certs/ca-certificates.crt
CMake Error at /home/nguyen/DEV/CINGULATA/PRIVATE/NGUYEN/build/optim/abc/tmp/abc-hgclone.cmake:30 (message):
  Failed to clone repository: 'https://bitbucket.org/alanmi/abc'

optim/CMakeFiles/abc.dir/build.make:89: recipe for target 'optim/abc/src/abc-stamp/abc-download' failed
make[2]: *** [optim/abc/src/abc-stamp/abc-download] Error 1
CMakeFiles/Makefile2:176: recipe for target 'optim/CMakeFiles/abc.dir/all' failed
make[1]: *** [optim/CMakeFiles/abc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 12%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/keys_all.cxx.o
[ 13%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/keys_share.cxx.o

**Comment by sergiu-carpov** [comment]
Same as #12

**Comment by thanhhainguyen15** [comment]
no ! It's not solved my issues ! Here the logs during installation 

USER:~/DEV/CINGULATA/PRIVATE/PUB$ sudo apt-get install mercurial
Reading package lists... Done
Building dependency tree       
Reading state information... Done
......................................
Preparing to unpack .../mercurial_3.7.3-1ubuntu1_amd64.deb ...
Unpacking mercurial (3.7.3-1ubuntu1) ...
Processing triggers for man-db (2.7.5-1) ...
Setting up libjs-excanvas (0.r3-4) ...
Setting up mercurial-common (3.7.3-1ubuntu1) ...
Setting up mercurial (3.7.3-1ubuntu1) ...

Creating config file /etc/mercurial/hgrc.d/hgext.rc with new version
USER:~/DEV/CINGULATA/PRIVATE/PUB$ rm -fr build/
USER:~/DEV/CINGULATA/PRIVATE/PUB$ mkdir build
USER:~/DEV/CINGULATA/PRIVATE/PUB$ cd build/
USER:~/DEV/CINGULATA/PRIVATE/PUB$ cmake ..
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
..........................................................
-- Found the following Boost libraries:
--   program_options
--   graph
-- Configuring done
-- Generating done
-- Build files have been written to: USER:~/DEV/CINGULATA/PRIVATE/PUB/build
USER:~/DEV/CINGULATA/PRIVATE/PUB$ make -j 8
Scanning dependencies of target fhe_fv
Scanning dependencies of target helper
Scanning dependencies of target abc
Scanning dependencies of target generator
[  1%] Building CXX object runtime/fhe_apps/src/CMakeFiles/helper.dir/helper.cxx.o
[  2%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/ciphertext.cxx.o
[  3%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/keygen.cxx.o
[  4%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/fhe_params.cxx.o
[  5%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/encdec.cxx.o
[  6%] Building CXX object circuit/generator/src/CMakeFiles/generator.dir/bit-tracker.cxx.o
[  7%] Creating directories for 'abc'
[  8%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/keys_all.cxx.o
[  9%] Performing download step (hg clone) for 'abc'
abort: could not find web.cacerts: /etc/ssl/certs/ca-certificates.crt
CMake Error at /home/nguyen/DEV/CINGULATA/PRIVATE/NGUYEN/build/optim/abc/tmp/abc-hgclone.cmake:30 (message):
  Failed to clone repository: 'https://bitbucket.org/alanmi/abc'


optim/CMakeFiles/abc.dir/build.make:89: recipe for target 'optim/abc/src/abc-stamp/abc-download' failed
make[2]: *** [optim/abc/src/abc-stamp/abc-download] Error 1
CMakeFiles/Makefile2:176: recipe for target 'optim/CMakeFiles/abc.dir/all' failed
make[1]: *** [optim/CMakeFiles/abc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 10%] Building CXX object circuit/generator/src/CMakeFiles/generator.dir/circuit.cxx.o
[ 11%] Building CXX object circuit/generator/src/CMakeFiles/generator.dir/node.cxx.o
[ 12%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/keys_share.cxx.o
[ 13%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/normal.cxx.o
[ 14%] Building CXX object circuit/generator/src/CMakeFiles/generator.dir/storage.cxx.o
[ 15%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/polyring.cxx.o
[ 16%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/rand_polynom.cxx.o
[ 17%] Building CXX object runtime/fhe_fv/src/CMakeFiles/fhe_fv.dir/uniform.cxx.o
[ 18%] Linking CXX static library libfhe_fv.a
[ 19%] Linking CXX static library ../../../libs/libgenerator.a
[ 19%] Built target fhe_fv
[ 19%] Built target generator
[ 20%] Linking CXX executable ../../../apps/helper
[ 20%] Built target helper
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by sergiu-carpov** [comment]
It's something with your certificates:
`abort: could not find web.cacerts: /etc/ssl/certs/ca-certificates.crt`
Try to clone abc with `hg clone https://bitbucket.org/alanmi/abc `, if it
doesn't work then it won't work in the makefile either.

**Comment by thanhhainguyen15** [comment]
Maybe the solution is worked 
your-host-name:/etc/mercurial$ sudo nano hgrc

[hostfingerprints]
api.media.atlassian.com = 00:fc:47:46:3e:b0:6d:4e:cb:da:33:8b:33:84:6a:35:17:2b:82:e7
bitbucket.org = 70:a7:44:ea:a9:ea:e8:69:16:ea:12:00:35:a9:a6:0e:ae:38:8e:f8
-------------------------------------------
compile your folder build again, and it works
build$ make -j 8
............................................
[100%] Built target multiplicity
