### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by thanhhainguyen15** [CEA-LIST/Cingulata#14]
Hi, 
I found a big bug during key generation, please tell me how to fix it ?

~/fhe/Cingulata/build/tests/hello$ ../../apps/generate_keys 
Floating point exception

-------------------------------------
OS : Ubuntu 16.04LTS
-------------------------------------
Using both configuration from wiki intall_os and specific versions as below, but this problem cannot be solved !
gmp-6.1.1.tar.bz2
mpir-2.7.2.tar.bz2
mpfr-4.0.1.tar.bz2
flint-2.5.2.tar.gz

**Comment by NanXiao** [comment]
@thanhhainguyen I think you should provide more detailed information: such as the core dump information, how to reproduce the bugs step by step, etc.

**Comment by ssmiler** [comment]
configuration problem, close #14

**Comment by ssmiler** [comment]
configuration problem, so closing issue
