### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by dimk1** [CEA-LIST/Cingulata#17]
During make I get the following error:

`jim@xps:~/Documents/[MyDecFiles]/Code/Cingulata/build$ make
[  5%] Built target generator
[  6%] Performing download step (hg clone) for 'abc'
applying clone bundle from https://api.media.atlassian.com/file/87d21905-22e2-4eb2-ba40-f84ee25aeb4b/binary?client=fa8179bc-0876-4538-9379-3b6f652769a8&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOnsidXJuOmZpbGVzdG9yZTpmaWxlOjg3ZDIxOTA1LTIyZTItNGViMi1iYTQwLWY4NGVlMjVhZWI0YiI6WyJyZWFkIl19LCJleHAiOjE1NTk4MjYxNjUsImlzcyI6ImZhODE3OWJjLTA4NzYtNDUzOC05Mzc5LTNiNmY2NTI3NjlhOCIsIm5iZiI6MTU1OTgyNTc0NX0.vXbE-tAtJU2nka8ItAr1pKGyonMTiCJisA967rmLXns
adding changesets
adding manifests
transaction abort!
rollback completed
abort: Input/output error: /home/jim/Documents/[MyDecFiles]/Code/Cingulata/build/optim/abc/src/abc/.hg/store/00manifest.d
CMake Error at /home/jim/Documents/[MyDecFiles]/Code/Cingulata/build/optim/abc/tmp/abc-hgclone.cmake:30 (message):
  Failed to clone repository: 'https://bitbucket.org/alanmi/abc'

optim/CMakeFiles/abc.dir/build.make:89: recipe for target 'optim/abc/src/abc-stamp/abc-download' failed
make[2]: *** [optim/abc/src/abc-stamp/abc-download] Error 1
CMakeFiles/Makefile2:176: recipe for target 'optim/CMakeFiles/abc.dir/all' failed
make[1]: *** [optim/CMakeFiles/abc.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

It seems that the page in https://bitbucket.org/alanmi/abc is no longer active so make fails.

**Comment by sergiu-carpov** [comment]
Thanks for reporting it.
In next weeks we will push a major revision of Cingulata which will fix this issue.

**Comment by ssmiler** [comment]
@dimk1 you can check for the new version. It is way easier now to compile cingulata with docker.

**Comment by bpradeep508** [comment]
can you tell me which step you are strucked

**Comment by ssmiler** [comment]
Closing issue. ABC points to github repository
