### ISSUE TITLE
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 208.67.222.222:53: read udp 10.171.3.31:35565->208.67.222.222:53: i/o timeout

### ISSUE THREAD

**Issue by bpradeep508** [CEA-LIST/Cingulata#18]

**Comment by ssmiler** [comment]
Cingulata image is not on docker.io You must build the image by yourself.

Take a look here https://github.com/CEA-LIST/Cingulata/wiki/Installation#cingulata-with-tfhe-library-backend

**Comment by bpradeep508** [comment]
I am trying to build image at that time showing this error

**Comment by ssmiler** [comment]
Does `docker run hello-world` work on you machine? 
If not, I think your docker installation has proxy issues.
Try to set a proxy server in file `/etc/default/docker`.

**Comment by ssmiler** [comment]
Issue not related to this repo
