### ISSUE TITLE
make' returned a non-zero code: 100

### ISSUE THREAD

**Issue by bpradeep508** [CEA-LIST/Cingulata#19]
Sending build context to Docker daemon  3.584kB
Step 1/10 : FROM ubuntu:18.04
 ---> a2a15febcdf3
Step 2/10 : RUN apt-get update -qq  && apt-get install --no-install-recommends -y     ca-certificates     cmake     g++     git     libboost-program-options-dev     make
 ---> Running in 7f039499a2cf
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease  Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease  Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package ca-certificates is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ca-certificates' has no installation candidate
E: Unable to locate package cmake
E: Unable to locate package git
E: Unable to locate package libboost-program-options-dev
E: Unable to locate package make
The command '/bin/sh -c apt-get update -qq  && apt-get install --no-install-recommends -y     ca-certificates     cmake     g++     git     libboost-program-options-dev     make' returned a non-zero code: 100

**Comment by ssmiler** [comment]
I suppose you host is ubuntu. There is a know issue of internet connection inside docker containers.
The 2 point (Fix the host's ...) from this post https://superuser.com/a/1335054 should fix your problem.

**Comment by bpradeep508** [comment]
problem not solved

**Comment by ssmiler** [comment]
What is your operating system?

**Comment by bpradeep508** [comment]
Ubuntu 16.04 lts

**Comment by ssmiler** [comment]
What is the contents of /etc/resolv.conf?

**Comment by ssmiler** [comment]
And what is the result of command `docker run ubuntu apt-get update` ?

**Comment by bpradeep508** [comment]
output     of   /etc/resolv.conf

**Comment by ssmiler** [comment]
You forgot to attach the output

**Comment by bpradeep508** [comment]
[image: Screenshot from 2019-09-06 21-44-29.png]

**Comment by ssmiler** [comment]
You should copy-paste the text from the terminal here

**Comment by bpradeep508** [comment]
Sending build context to Docker daemon 3.584kB
Step 1/10 : FROM ubuntu:18.04
---> a2a15febcdf3
Step 2/10 : RUN apt-get update -qq && apt-get install
--no-install-recommends -y ca-certificates cmake g++ git
libboost-program-options-dev make
---> Running in 7f039499a2cf
W: Failed to fetch
http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease Temporary
failure resolving 'archive.ubuntu.com'
W: Failed to fetch
http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease Temporary
failure resolving 'archive.ubuntu.com'
W: Failed to fetch
http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease Temporary
failure resolving 'archive.ubuntu.com'
W: Failed to fetch
http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease Temporary
failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones
used instead.
Reading package lists...
Building dependency tree...
Reading state information...
Package ca-certificates is not available, but is referred to by another
package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ca-certificates' has no installation candidate
E: Unable to locate package cmake
E: Unable to locate package git
E: Unable to locate package libboost-program-options-dev
E: Unable to locate package make
The command '/bin/sh -c apt-get update -qq && apt-get install
--no-install-recommends -y ca-certificates cmake g++ git
libboost-program-options-dev make' returned a non-zero code: 100

**Comment by ssmiler** [comment]
I meant the contents of /etc/resolv.conf and the output of command `docker run ubuntu apt-get update`

**Comment by bpradeep508** [comment]
*/etc/resolv.conf  file content*

# Dynamic resolv.conf(5) file for glibc resolver(3) generated by
resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 172.16.1.180
nameserver 172.16.1.164
nameserver 8.8.8.8



*docker run ubuntu apt-get update output*

Err:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
  Temporary failure resolving 'security.ubuntu.com'
Err:2 http://archive.ubuntu.com/ubuntu bionic InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Err:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
  Temporary failure resolving 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/bionic/InRelease
 Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch
http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  Temporary
failure resolving 'archive.ubuntu.com'
W: Failed to fetch
http://archive.ubuntu.com/ubuntu/dists/bionic-backports/InRelease
 Temporary failure resolving 'archive.ubuntu.com'
W: Failed to fetch
http://security.ubuntu.com/ubuntu/dists/bionic-security/InRelease
 Temporary failure resolving 'security.ubuntu.com'
W: Some index files failed to download. They have been ignored, or old ones
used instead.

**Comment by ssmiler** [comment]
There is clearly an issue with your docker configuration. Containers cannot acces internet.
If you can't fix this problem I advise to compile Cingulata directly. Take a look at Dockerfile.tfhe in the root directory. Install required packages and compile tfhe library (the 'RUN' commands). Afterwards compile Cingulata with tfhe backend (dockerfile CMD command):
```
mkdir build
cd build
cmake -DTFHE_PATH=<tfhe path> ..
make
```

**Comment by bpradeep508** [comment]
can you send me steps because tfhe installed in my system. i tried in other
system with  ubuntu 18.04 getting same error

**Comment by ssmiler** [comment]
Issue not related to this repo
