### ISSUE TITLE
after completion   Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by bpradeep508** [CEA-LIST/Cingulata#20]
Sending build context to Docker daemon  3.584kB
Step 1/9 : FROM ubuntu:18.04
 ---> a2a15febcdf3
Step 2/9 : RUN apt-get update -qq  && apt-get install --no-install-recommends -y     ca-certificates     cmake     g++     git     libboost-program-options-dev     make
 ---> Using cache
 ---> 4e1950b65b54
Step 3/9 : ARG uid=1000
 ---> Using cache
 ---> 12fe7247bab5
Step 4/9 : ARG uname=cingu
 ---> Using cache
 ---> ac23c3dbfd4c
Step 5/9 : RUN useradd -u $uid $uname
 ---> Running in 99bf835caae0
useradd: UID 0 is not unique
The command '/bin/sh -c useradd -u $uid $uname' returned a non-zero code: 4
(base) root@user-HP-Z240-Tower-Workstation:/home/user/Cingulata# docker run -it --rm -v $(pwd):/cingu cingulata:tfheCMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find TFHE (missing: TFHE_INCLUDE_DIR TFHE_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindTFHE.cmake:16 (find_package_handle_standard_args)
  CMakeLists.txt:28 (find_package)

-- Configuring incomplete, errors occurred!
See also "/cingu/build_tfhe/CMakeFiles/CMakeOutput.log"

**Comment by ssmiler** [comment]
At step 5 the dockerfile tries to add an user with id 0 (root) which already exists in the container. This case was not foreseen. Try to use command `docker build -t cingulata:tfhe -f Dockerfile.tfhe --build-arg uid=1000 .` instead.

**Comment by bpradeep508** [comment]
(base) root@user-HP-Z240-Tower-Workstation:/home/user/Cingulata# docker run -it --rm -v $(pwd):/cingu cingulata:tfhe
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find TFHE (missing: TFHE_INCLUDE_DIR TFHE_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindTFHE.cmake:18 (find_package_handle_standard_args)
  CMakeLists.txt:28 (find_package)


-- Configuring incomplete, errors occurred!
See also "/cingu/build_tfhe/CMakeFiles/CMakeOutput.log".

**Comment by ssmiler** [comment]
Can you copy the output of docker creation command `docker build -t cingulata:tfhe -f Dockerfile.tfhe --build-arg uid=1000 .` ?

**Comment by bpradeep508** [comment]
Sending build context to Docker daemon  3.584kB
Step 1/9 : FROM ubuntu:18.04
 ---> a2a15febcdf3
Step 2/9 : RUN apt-get update -qq  && apt-get install
--no-install-recommends -y     ca-certificates     cmake     g++     git
  libboost-program-options-dev     make
 ---> Using cache
 ---> 4e1950b65b54
Step 3/9 : ARG uid=1000
 ---> Using cache
 ---> 12fe7247bab5
Step 4/9 : ARG uname=cingu
 ---> Using cache
 ---> ac23c3dbfd4c
Step 5/9 : RUN useradd -u $uid $uname
 ---> Using cache
 ---> cb0c6bd04096
Step 6/9 : USER $uname
 ---> Using cache
 ---> eff08f7dff98
Step 7/9 : ENV build_dir=build_tfhe
 ---> Using cache
 ---> 61e583149f4f
Step 8/9 : CMD mkdir -p /cingu/$build_dir  && cd /cingu/$build_dir  &&
cmake -DTFHE_PATH=/home/user/tfhe ..  && make
 ---> Using cache
 ---> 0c1d65e6f303
Step 9/9 : WORKDIR /cingu/
 ---> Using cache
 ---> ae870a3c7969
Successfully built ae870a3c7969
Successfully tagged cingulata:tfhe

**Comment by ssmiler** [comment]
I don't see the TFHE compilation step. 

I see that you wanted to use your own install of tfhe. You cannot specify a host-machine path inside the dockerfile. Use the original version of Dockerfile.tfhe. It should work fine

**Comment by bpradeep508** [comment]
tfhe already installed in the location   /home/user/tfhe so i am not
executing tfhe installtion


# install dependencies
RUN apt-get update -qq \
 && apt-get install --no-install-recommends -y \
    ca-certificates \
    cmake \
    g++ \
    git \
    libboost-program-options-dev \
    make

# clone and compile TFHE library
#RUN git clone --recurse-submodules --branch=master
https://github.com/tfhe/tfhe.git /home/user/tfhe \
 #&& cd tfhe \
# && make

# add user
ARG uid=1000
ARG uname=cingu
RUN useradd -u $uid $uname

USER $uname

ENV build_dir=build_tfhe

# compilation command
CMD mkdir -p /cingu/$build_dir \
 && cd /cingu/$build_dir \
 && cmake -DTFHE_PATH=/home/user/tfhe .. \
 && make

WORKDIR /cingu/

**Comment by ssmiler** [comment]
You should specify TFHE installation directory during docker container execution
`docker run -it --rm -v $(pwd):/cingu -v /home/user/tfhe:/home/user/tfhe cingulata:tfhe`
Although I'm not sure this will work.

**Comment by bpradeep508** [comment]
Input encryption
TFHE key generation
Homomorphic execution...
Number of executions:
 encode  :      8
 encrypt :      0
 decrypt :      0
 read    :     16
 write   :     16
 ------------------
 not     :      0
 ------------------
 and     :      7
 xor     :     28
 nand    :      0
 andyn   :      0
 andny   :      0
 or      :      0
 nor     :      0
 oryn    :      0
 orny    :      0
 xnor    :      0
 and
  + xor
  + nand
  + andyn
  + andny
  + or
  + nor
  + oryn
  + orny
  + xnor =     35
 ------------------
 mux     :      0
 ------------------

real 0m0.421s
user 0m0.369s
sys 0m0.052s
Output decryption
8

**Comment by bpradeep508** [comment]
[image: image.png]


Many Many  ....
Thanks,  you are  helped  me in every step of the installation

**Comment by ssmiler** [comment]
You're welcome.
Can you close the opened issues?

**Comment by bpradeep508** [comment]
sure sir

**Comment by bpradeep508** [comment]
sir can you send personnel mail id
this my mail id:pradeepkumarreddy.bukka@gmail.com

**Comment by ssmiler** [comment]
My email is in my profile if this is what you want.

**Comment by bpradeep508** [comment]
/home/user/Cingulata# docker run -it --rm -v $(pwd):/cingu
/home/user/tfhe:/home/user/tfhe bash -c "cd build_tfhe/tests/tfhe/hello &&
bash run.sh"
docker: invalid reference format.
See 'docker run --help'.

**Comment by ssmiler** [comment]
The host TFHE installation path must be given only during docker image build. When you want to execute an example inside the docker the TFHE installation path should not be specified. So use this command instead:
```
docker run -it --rm -v $(pwd):/cingu cingulata:tfhe bash -c "cd build_tfhe/tests/tfhe/hello && bash run.sh"
```

**Comment by bpradeep508** [comment]
Cingulata$ docker run -it --rm -v $(pwd):/cingu cingulata:tfhe bash -c "cd
build_tfhe/tests/tfhe/hello && bash run.sh"
Input encryption
TFHE key generation
/cingu/build_tfhe/apps/tfhe-keygen: error while loading shared libraries:
libtfhe-spqlios-avx.so: cannot open shared object file: No such file or
directory
./tfhe-hello-encrypt: error while loading shared libraries:
libtfhe-spqlios-avx.so: cannot open shared object file: No such file or
directory
Homomorphic execution...
./tfhe-hello-exec: error while loading shared libraries:
libtfhe-spqlios-avx.so: cannot open shared object file: No such file or
directory

real 0m0.006s
user 0m0.001s
sys 0m0.000s
Output decryption
./tfhe-hello-decrypt: error while loading shared libraries:
libtfhe-spqlios-avx.so: cannot open shared object file: No such file or
directory

**Comment by ssmiler** [comment]
I cannot find the TFHE library. Are you sure you have not deleted TFHE folder?
I strongly advise you to compile Cingulata using instructions from here https://github.com/CEA-LIST/Cingulata/wiki/Installation#cingulata-with-tfhe-library-backend

**Comment by bpradeep508** [comment]
Tfhe not installing
docker build --build-arg http_proxy=http://172.16.2.30:8080 -t
cingulata:tfhe -f Dockerfile.tfhe --build-arg uid=1000 .
Sending build context to Docker daemon  3.584kB
Step 1/10 : FROM ubuntu:18.04
 ---> a2a15febcdf3
Step 2/10 : RUN apt-get update -qq  && apt-get install
--no-install-recommends -y     ca-certificates     cmake     g++     git
  libboost-program-options-dev     make
 ---> Using cache
 ---> bdbf13fbaf28
Step 3/10 : RUN git clone https://github.com/tfhe/tfhe /tfhe  && cd tfhe
 && make
 ---> Running in 451739326f6f
Cloning into '/tfhe'...
fatal: unable to access 'https://github.com/tfhe/tfhe/': Failed to connect
to github.com port 443: Connection timed out
The command '/bin/sh -c git clone https://github.com/tfhe/tfhe /tfhe  && cd
tfhe  && make' returned a non-zero code: 128

**Comment by ssmiler** [comment]
Have you tried other methods to set the proxy server? https://docs.docker.com/network/proxy/

May be you should specify the https proxy also.

**Comment by bpradeep508** [comment]
Configured as per the documentation still same problem

**Comment by ssmiler** [comment]
I have no more ideas on how you can solve the proxy issue.

By the way, why don't you use TFHE as an external project as you did before?
The hello world example with TFHE was working well https://github.com/CEA-LIST/Cingulata/issues/20#issuecomment-529200097

**Comment by bpradeep508** [comment]
I tried the as external but giving errors in the middle of execution

**Comment by bpradeep508** [comment]
this is my command
 docker run -it --rm -v $(pwd):/cingu -v /home/user/tfhe:/home/user/tfhe
cingulata:tfhe bash -c "cd build_tfhe/tests/tfhe/hello && bash run.sh"

giving same output but after changing parameters in *"run.sh.in
<http://run.sh.in>"*

**Comment by ssmiler** [comment]
Try to change tfhe path inside docker:
`docker run -it --rm -v $(pwd):/cingu -v /home/user/tfhe:/tfhe cingulata:tfhe bash -c "cd build_tfhe/tests/tfhe/hello && bash run.sh"`

**Comment by bpradeep508** [comment]
sir how to change in docker file i cant understand

**Comment by ssmiler** [comment]
I meant the path inside docker container where tfhe is mounted. In your command instead of `-v /home/user/tfhe:/home/user/tfhe` use `-v /home/user/tfhe:/tfhe`

**Comment by bpradeep508** [comment]
after execution  error as fallows
docker run -it --rm -v $(pwd):/cingu -v /home/user/tfhe:/tfhe
cingulata:tfhe bash -c "cd build_tfhe/tests/tfhe/hello && bash run.sh"
Input encryption
TFHE key generation
/cingu/build_tfhe/apps/tfhe-keygen: error while loading shared libraries:
libtfhe-spqlios-avx.so: cannot open shared object file: No such file or
directory
./tfhe-hello-encrypt: error while loading shared libraries:
libtfhe-spqlios-avx.so: cannot open shared object file: No such file or
directory
Homomorphic execution...
./tfhe-hello-exec: error while loading shared libraries:
libtfhe-spqlios-avx.so: cannot open shared object file: No such file or
directory

real 0m0.000s
user 0m0.000s
sys 0m0.000s
Output decryption
./tfhe-hello-decrypt: error while loading shared libraries:
libtfhe-spqlios-avx.so: cannot open shared object file: No such file or
directory

**Comment by ssmiler** [comment]
Try to remove `build_tfhe` directory and do `docker run -it --rm -v $(pwd):/cingu -v /home/user/tfhe:/tfhe
cingulata:tfhe`

**Comment by bpradeep508** [comment]
~/Cingulata$ docker run -it --rm -v $(pwd):/cingu -v /home/user/tfhe:/tfhe
cingulata:tfhe
-- include : /home/user/tfhe/src/include
-- lib     : /home/user/tfhe/build/libtfhe/libtfhe-spqlios-avx.so
BUILD_DOC                  OFF
BUILD_ONLY_COMMON          OFF
USE_BFV                    OFF
USE_TFHE                   ON
TFHE_PATH                  /home/user/tfhe
ENABLE_UNITTEST            OFF
INIT_ABC_MODULE            OFF
INIT_CINGU_PARAM_MODULE    OFF
INIT_GOOGLETEST_MODULE     OFF
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
-- Configuring done
-- Generating done
-- Build files have been written to: /cingu/build_tfhe
[ 53%] Built target common
[ 58%] Built target simple_test
[ 62%] Built target test_cpp_oper
[ 67%] Built target tfhe_bit_exec
Scanning dependencies of target tfhe-keygen
[ 69%] Building CXX object
runtime/tfhe/CMakeFiles/tfhe-keygen.dir/src/keygen.cxx.o
/cingu/runtime/tfhe/src/keygen.cxx:26:10: fatal error: tfhe.h: No such file
or directory
 #include <tfhe.h>
          ^~~~~~~~
compilation terminated.
runtime/tfhe/CMakeFiles/tfhe-keygen.dir/build.make:62: recipe for target
'runtime/tfhe/CMakeFiles/tfhe-keygen.dir/src/keygen.cxx.o' failed
make[2]: *** [runtime/tfhe/CMakeFiles/tfhe-keygen.dir/src/keygen.cxx.o]
Error 1
CMakeFiles/Makefile2:364: recipe for target
'runtime/tfhe/CMakeFiles/tfhe-keygen.dir/all' failed
make[1]: *** [runtime/tfhe/CMakeFiles/tfhe-keygen.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ssmiler** [comment]
And this one `docker run -it --rm -v $(pwd):/cingu -v /home/user/tfhe:/home/user/tfhe`

**Comment by bpradeep508** [comment]
~/Cingulata$ docker run -it --rm -v $(pwd):/cingu -v
/home/user/tfhe:/home/user/tfhe
"docker run" requires at least 1 argument.

**Comment by ssmiler** [comment]
Closing old issue
