### ISSUE TITLE
subtraction not giving correct result

### ISSUE THREAD

**Issue by bpradeep508** [CEA-LIST/Cingulata#25]
a=100 b=90
actual result a-b=10 giving correct resutl
actual result b-a= -10 giving result as  65456

**Comment by ssmiler** [comment]
Can you put the code you use here?

**Comment by bpradeep508** [comment]
/*encrypt*/
int main(int argc, char* argv[]) {
  if (argc < 3) {
    cerr << "Usage: " << argv[0] << " <a> <b>" << endl;
    exit(-1);
  }

  /* get input values */
  int a_val = 10;
  int b_val = 90;

  /* Only tfhe bit executor is needed for encryption/decryption and IO
operations  */
  CiContext::set_bit_exec(make_shared<TfheBitExec>("tfhe.sk",
TfheBitExec::Secret));

  CiInt a{a_val, 16, false};
  CiInt b{b_val, 16, false};

  a.encrypt().write("a");
  b.encrypt().write("b");
}

                  /*hello.cxx*/
int main() {
  /* Set context to tfhe bit executor and size minimized integer
   * operations */
  CiContext::set_config(
      make_shared<decorator::Attach<TfheBitExec,
decorator::Stat<IBitExecFHE>>>(
          "tfhe.pk", TfheBitExec::Public),
      make_shared<IntOpGenSize>());

  CiInt a{0, 16, false};   // create from unsigned 8-bit template
  CiInt b{0, 16, false}; // manually specify value, size and signedness
  CiInt c{0, 16, false}; // automatically determine size and signedness
from value

  a.read("a");
  b.read("b");

  c = a - b;
  // c = a * a * b - a;

  c.write("c");

  CiContext::get_bit_exec_t<decorator::Stat<IBitExecFHE>>()->print();
}

         /* decrypt*/

int main() {
  /* Only tfhe bit executor is needed for encryption/decryption and IO
operations  */
  CiContext::set_bit_exec(make_shared<TfheBitExec>("tfhe.sk",
TfheBitExec::Secret));

  CiInt c{(uint16_t)-1};  // automatically determine size and signedness
from value

  c.read("c").decrypt();

  uint16_t c_val = c.get_val();

  cout << c_val << endl;
}

**Comment by sergiu-carpov** [comment]
You must use signed CiInts (last parameter to CiInt constructor should be
true) and use int16_t instead of uint16_t in decryption.

Le dim. 8 mars 2020 à 04:54, bpradeep508 <notifications@github.com> a
écrit :
