### ISSUE TITLE
corrupted size .vs. prev size error

### ISSUE THREAD

**Issue by manips2002** [CEA-LIST/Cingulata#28]
Hi, I got this error while I was developing our own application using cingulata. 
corrupted size vs. prev_size
run.sh: line 41:     9 Aborted                 (core dumped) ./tfhe-$NAME-exec

Has anyone else encountered this before with cingulata? how do I work on fixing this? I will be happy to share code for my application if needed..

**Comment by ssmiler** [comment]
Sharing the code you want to execute will be necessary.
