### ISSUE TITLE
The question about stream template functions in sliced-integer.hxx

### ISSUE THREAD

**Issue by NanXiao** [CEA-LIST/Cingulata#3]
Hi all,

The template `istream` and `ostream` functions defined in [sliced-integer.hxx](https://github.com/CEA-LIST/Cingulata/blob/ff9ee947a636d6572236b70abaa1ffc51fc8f550/circuit/generator/include/sliced-integer.hxx#L300):   

```
/*! \brief implementation of the formatted read operation */
template<typename BitType>
std::istream& operator>>
  (std::istream &in_io,
   BitType &value_o)
{
  value_o.read (in_io);
  return in_io;
}

/*! \brief implementation of the formatted write operation */
template<typename BitType>
std::ostream& operator<<
  (std::ostream &out_io,
   const BitType &value_i)
{
  value_i.write (out_io);
  return out_io;
}
```

will cause build error when source code who includes `sliced-integer.hxx`  and do input and output some basic data types, such as string. For example:  

    #include <integer.hxx>
    ......
    string a;
    cout << a;

Compile it:  
```
error: ambiguous overload for ‘operator<<’ (operand types are ‘std::ostream {aka std::basic_ostream<char>}’ and ‘std::__cxx11::string {aka std::__cxx11::basic_string<char>}’)
  cout << a;
  ~~~~~^~~~
In file included from /home/xiaonan/Cingulata/circuit/generator/src/../include/integer.hxx:30:0,
                 from /home/xiaonan/Cingulata/tests/trivium/trivium.cxx:25:
/home/xiaonan/Cingulata/circuit/generator/src/../include/sliced-integer.hxx:312:15: note: candidate: std::ostream& operator<<(std::ostream&, const BitType&) [with BitType = std::__cxx11::basic_string<char>; std::ostream = std::basic_ostream<char>]
 std::ostream& operator<<
               ^~~~~~~~
In file included from /usr/include/c++/7.2.1/string:52:0,
                 from /usr/include/c++/7.2.1/bits/locale_classes.h:40,
                 from /usr/include/c++/7.2.1/bits/ios_base.h:41,
                 from /usr/include/c++/7.2.1/ios:42,
                 from /usr/include/c++/7.2.1/ostream:38,
                 from /usr/include/c++/7.2.1/iostream:39,
                 from /home/xiaonan/Cingulata/tests/trivium/trivium.cxx:22:
/usr/include/c++/7.2.1/bits/basic_string.h:6272:5: note: candidate: std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, const std::__cxx11::basic_string<_CharT, _Traits, _Alloc>&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]
     operator<<(basic_ostream<_CharT, _Traits>& __os,
```

Similar for input string:  

    string a;
    cin >> a;

So is it really necessary to define these two template functions?

Thanks very much!

Best  Regards
Nan Xiao

**Comment by renaud-sirdey** [comment]
Dear Nan,

This is connected to my latter comment on issue #2.

In a Cingulata program, any value not read from the standard input into IntegerX variables would be considered constant and triggers simplifications in the resulting boolean circuit. For this reason, it is necessary to avoid IOs on any other types and to define clear-domain constant values explictly into the program.

Still, clear-domain values may still be passed through IOs on IntegerX type (perhaps a tutorial is needed to explain how to do these more advanced IOs, we’ll work on this soon) and in this case do not influence the structure of the circuit. 

Hope this helps!

Best regards, Renaud

**Comment by NanXiao** [comment]
Hi Renaud,

Got it! Thanks very much for your time and help!

Best Regards
Nan Xiao
