### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'   what():  std::bad_alloc run.sh: line 38:     9 Aborted 

### ISSUE THREAD

**Issue by bpradeep508** [CEA-LIST/Cingulata#33]
int main() {
  CiContext::set_config(
      make_shared<decorator::Attach<TfheBitExec, decorator::Stat<IBitExecFHE>>>(
          "tfhe.pk", TfheBitExec::Public),
      make_shared<IntOpGenSize>());  
 vector<CiInt> a1(6, CiInt::u8);
 vector<CiInt> b1(6, CiInt::u8);
 vector<CiInt> c1(6, CiInt::u8);   
    for(int i=0;i<6;i++)
   {
      a1[i].read("a"+to_string(i));
      b1[i].read("b"+to_string(i)); 
  } 
     c1=add(a1,b1);
       for(int i=0;i<6;i++)
   {
      c1[i].write("c"+to_string(i));
  } 
  CiContext::get_bit_exec_t<decorator::Stat<IBitExecFHE>>()->print();
}
 vector<CiInt> add(vector<CiInt>& a1,vector<CiInt>& b1)
{
 vector<CiInt> temp{6,CiInt::u8};
    for (int i=0;i<6;i++)
{
temp[i]=a1[i]*b1[i];
}  
return temp;
}

**Comment by ssmiler** [comment]
Line 5 of your code. An integer operations generator is needed. Use `make_shared<IntOpGenSize>()` instead of `make_shared()`.

**Comment by bpradeep508** [comment]
after changing also giving the same error
