### ISSUE TITLE
In docker mode  Cingulata  Bfv  does not compile any more

### ISSUE THREAD

**Issue by patrick-ruf** [CEA-LIST/Cingulata#35]
Hello 
I cloned the last github Cingulata  . In docker mode  Cingulata  Bfv  does not compile any more . In fact  abc optimisation fails  

Please find below my traces 
 
Traceback (most recent call last):
  File "/cingu/build_bfv/tests/../optim/abc_optimize.py", line 77, in <module>
    circuit = utils.readBlifFile(args.input_file)
  File "/cingu/build_bfv/optim/utils.py", line 32, in readBlifFile
    return parseBlif(lines)
  File "/cingu/build_bfv/optim/utils.py", line 68, in parseBlif
    G.nodes()[out]['gate'] = True
TypeError: list indices must be integers or slices, not str
tests/old_bfv/wiretap/CMakeFiles/old-bfv-wiretap.dir/build.make:64: recipe for target 'tests/old_bfv/wiretap/old-bfv-wiretap-opt.blif' failed
make[2]: *** [tests/old_bfv/wiretap/old-bfv-wiretap-opt.blif] Error 1
CMakeFiles/Makefile2:3026: recipe for target 'tests/old_bfv/wiretap/CMakeFiles/old-bfv-wiretap.dir/all' failed

It seems that last merged modifications    « Fixed for NetworkX 2.4 »  are involved.

I did  a git clone + git checkout of  commit id (4 th june) without these changes eb028240000ee4d4cbc7b1a1aacfaf62ca1f6e5f, in docker compilation the whole  bfv compilation was succcesful.

The  information i have got for python-networks in docker
 
crypto@is154572:~/essaie/Cingulata$ docker run -it --env="DISPLAY" --env="QT_X11_NO_MITSHM=1" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw"   --rm -v $(pwd):/cingu cingulata:bfv bash
cingu@d4e68dd02df2:/cingu$ apt-cache policy python3-networkx
python3-networkx:
  Installed: 1.11-1ubuntu3
  Candidate: 1.11-1ubuntu3
  Version table:
 *** 1.11-1ubuntu3 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
        100 /var/lib/dpkg/status
     1.11-1ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

Regards 
Patrick RUF

**Comment by ssmiler** [comment]
@patrick-ruf is the issue still present on the master branch?

**Comment by patrick-ruf** [comment]
New installation method does not work  
during docker build -t cingulata:bfv -f Dockerfile.bfv --build-arg uid=$(id -u) .
and exception occurs

Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.36.11-2) ...
Removing intermediate container 37f38fb4fbe3
 ---> e02883d11ae9
Step 4/11 : RUN pip3 install     networkx     numpy
 ---> Running in 9fe7ff506cb4
Collecting networkx
  Downloading https://files.pythonhosted.org/packages/9b/cd/dc52755d30ba41c60243235460961fc28022e5b6731f16c268667625baea/networkx-2.5-py3-none-any.whl (1.6MB)
Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/filewrapper.py", line 60, in read
    data = self.__fp.read(amt)
  File "/usr/lib/python3.6/http/client.py", line 463, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 507, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read

**Comment by patrick-ruf** [comment]
Purge container . 
Remove cingulata git clone again  . Second and third  try   build  is oK  
Compiling Ok

Test Ok bfv hello
I will do other bfv tests  for tommorow.

ragrds patrick

**Comment by ssmiler** [comment]
Close the issue if all good, thx

**Comment by patrick-ruf** [comment]
all test bfv ok under tests/bfv ok 
Thie issue is closed
