### ISSUE TITLE
The abstract layer for back-end library

### ISSUE THREAD

**Issue by NanXiao** [CEA-LIST/Cingulata#4]
Hi all,

Greetings from me!

I check all FHE apps, such as [encrypt](https://github.com/CEA-LIST/Cingulata/blob/ff9ee947a636d6572236b70abaa1ffc51fc8f550/runtime/fhe_apps/src/encrypt.cxx#L26), [decrypt](https://github.com/CEA-LIST/Cingulata/blob/ff9ee947a636d6572236b70abaa1ffc51fc8f550/runtime/fhe_apps/src/decrypt.cxx#L26) all include `fv.hxx`, so if I want to integrate other FHE libraries, e.g., `HElib`, I must modify all these FHE apps.  

So is there possible to implement an abstract layer, such as [HEAT](https://github.com/bristolcrypto/HEAT/blob/master/API.h)? If I substitute the back-end library, the FHE apps won't need be changed.

Thanks in advance!

Best Regards
Nan Xiao

**Comment by renaud-sirdey** [comment]
Dear Nan,

We are indeed working on a more abstract HE layer but it will come around June as we are planning to release a new backend with an additional support for the fast-bootstrapping TFHE library (https://github.com/tfhe/tfhe).

Still, we did not wanted to delay the first release of the compiler until this is ready.

Best regs, Renaud

PS : by the way, thanks for your first round of feedback! It's very nice to start having some :-)

**Comment by NanXiao** [comment]
Hi Renaud,

Thanks very much for your time and detailed explanation!

Best Regards
Nan Xiao
