### ISSUE TITLE
missing depencency on readline

### ISSUE THREAD

**Issue by ticapix** [CEA-LIST/Cingulata#5]
Hi,

In order to compile CMakeFiles/abc.dir/src/base/main/mainUtils.c.o, libreadline-dev needs to be installed.
It would be nice to add find_package(READLINE REQUIRED) in the CMakeList.txt

**Comment by sergiu-carpov** [comment]
Hi,
thanks for your message.
Actually, there is no need for readline library in our usage of ABC.
I have updated the cmake file accordingly to not use it.
Regards,
Sergiu
